FROM logstash:5
RUN logstash-plugin install logstash-input-log4j
RUN logstash-plugin install logstash-output-log4j
RUN logstash-plugin install logstash-filter-json
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
